name: CI - DevSecOps Pipeline

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-and-scan:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: us-west-1
      AWS_ACCOUNT_ID: 471112626077
      ECR_REGISTRY: 471112626077.dkr.ecr.us-west-1.amazonaws.com
      ECR_REPOSITORY: netflix-clone
      IMAGE_TAG: ${{ github.sha }}
      IMAGE_URI: 471112626077.dkr.ecr.us-west-1.amazonaws.com/netflix-clone:${{ github.sha }}

    steps:
      # -------------------------
      # Checkout
      # -------------------------
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # -------------------------
      # Node setup
      # -------------------------
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        working-directory: app
        run: yarn install --frozen-lockfile

      # -------------------------
      # SCA â€“ Dependency scanning
      # -------------------------
      - name: OWASP Dependency Check
        uses: dependency-check/Dependency-Check_Action@main
        with:
          project: "netflix-clone"
          path: "app"
          format: "HTML"
          out: "dependency-check-report"
          args: >
            --enableExperimental

      # -------------------------
      # Static code analysis
      # -------------------------
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2
        with:
          args: >
            -Dsonar.projectKey=TsembA_netflix-clone
            -Dsonar.organization=tsemba
            -Dsonar.sources=app
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      # -------------------------
      # Build container image
      # -------------------------
      - name: Build Docker image
        run: |
          docker build -t $IMAGE_URI ./app

      # -------------------------
      # Container security gate
      # -------------------------
      - name: Trivy image scan
        uses: aquasecurity/trivy-action@0.20.0
        with:
          image-ref: ${{ env.IMAGE_URI }}
          severity: CRITICAL,HIGH
          exit-code: 1
          ignore-unfixed: true

      # -------------------------
      # AWS authentication (OIDC)
      # -------------------------
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::471112626077:role/github-actions-ecr
          aws-region: us-west-1

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      # -------------------------
      # Push image to ECR
      # -------------------------
      - name: Push image to ECR
        run: |
          docker push $IMAGE_URI
